[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
governance = "9GqiBXHh7e5gREwHU6PKHDaQsLuYfqHQ2az2sBLXdaTv"

[programs.devnet]
governance = "9GqiBXHh7e5gREwHU6PKHDaQsLuYfqHQ2az2sBLXdaTv"

[programs.testnet]
governance = "9GqiBXHh7e5gREwHU6PKHDaQsLuYfqHQ2az2sBLXdaTv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "keys/authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
